services:
  api:
    image: ghcr.io/lukynmatuska/sktorrent-autodownloader:latest
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    #   args:
    #     USER_ID: 1000
    #     GROUP_ID: 1000
    restart: always
    ports:
      - "8000:80"
    environment:
      - CORS_ORIGINS
      - SKTORRENT_USERNAME
      - SKTORRENT_PASSWORD
      - QBT_URL
      - QBT_LOGIN
      - QBT_PASSWORD
      - TZ
    stdin_open: true  # -i
    tty: true         # -t
